name: Playwright E2E
on:
  push:
    branches: [master]
    paths: ['client/web/**']
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: { node-version: 18.x }
      - uses: pnpm/action-setup@v2
        with: { version: 8.15.8 }
      - run: pnpm install --frozen-lockfile
      - run: cd client/web/e2e/playwright && pnpm install
      - run: cd client/web/e2e/playwright && pnpm exec playwright install --with-deps
      - run: cd client/web/e2e/playwright && pnpm test
